Repository DeveloperKhan/pogo-web, pull requests merged in 2021-01, with the labels that each got.

#13 Fixed trio selector logic
  src/components/select/Select.tsx
Labels: frontend

#17 update energy for current Poke
  pages/game/[room].tsx
Labels: backend, frontend

#14 Charge move buttons
  .env.development
  .gitignore
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/end/[end].tsx
  pages/game/[room].tsx
  pages/game/style.module.scss
  pages/index.tsx
  pages/matchup/[room].tsx
  pages/style.module.scss
  pages/team.tsx
  src/common/actions/userAPIActions.ts
  src/common/css/colors.scss
  src/common/css/layout.scss
  src/components/charged/Charged.tsx
  src/components/charged/charged.module.scss
  src/components/field/Character.tsx
  src/components/form/Form.tsx
  src/components/header/Header.tsx
  src/components/header/header.module.scss
  src/components/icon/icons/bug.svg
  src/components/icon/icons/dark.svg
  src/components/icon/icons/dragon.svg
  src/components/icon/icons/electric.svg
  src/components/icon/icons/fairy.svg
  src/components/icon/icons/fighting.svg
  src/components/icon/icons/fire.svg
  src/components/icon/icons/flying.svg
  src/components/icon/icons/ghost.svg
  src/components/icon/icons/grass.svg
  src/components/icon/icons/ground.svg
  src/components/icon/icons/ice.svg
  src/components/icon/icons/index.ts
  src/components/icon/icons/menu.svg
  src/components/icon/icons/normal.svg
  src/components/icon/icons/poison.svg
  src/components/icon/icons/psychic.svg
  src/components/icon/icons/rock.svg
  src/components/icon/icons/steel.svg
  src/components/icon/icons/water.svg
  src/components/layout/Layout.tsx
  src/components/layout/layout.module.scss
  src/components/shield/Shield.tsx
  src/components/stepper/Stepper.tsx
  src/components/stepper/stepper.module.scss
  src/components/switch/switch.module.scss
  src/config/index.ts
  src/context/IdContext.tsx
  src/context/UserContext.tsx
  src/firebase.ts
Labels: WIP, frontend
